dist: bionic

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_b9975b9e73b5_key -iv $encrypted_b9975b9e73b5_iv
  -in travis-ci-key.enc -out travis-ci-key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./travis-ci-key
- echo -e "Host teamprojectuam.tk\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./travis-ci-key
- touch database/brapi_db/PlantPhenoDB.psql

script:
- docker-compose up -d --build

after_success:
- docker ps 
- ssh -i travis-ci-key plantphenoadmin@teamprojectuam.tk "cd /opt/brAPI_IPGPAS && sudo git checkout dev && sudo git pull && docker-compose up -d --build" 
