dist: bionic

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_b6ce6aea37aa_key -iv $encrypted_b6ce6aea37aa_iv
  -in travis-ci-key.enc -out .\\travis-ci-key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./travis-ci-key
- echo -e "Host teamprojectuam.tk\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./travis-ci-key
- ssh -i ./travis-ci-key plantphenoadmin@teamprojectuam.tk pwd
- touch database/brapi_db/PlantPhenoDB.psql

script:
- docker-compose up -d --build

after_success:
- docker ps
- docker-compose down
