FROM openjdk:8-jre-alpine3.9
WORKDIR /brapi-management-service
COPY target/brapimanagementservice-0.0.1-SNAPSHOT.jar /brapi-management-service
EXPOSE 8081
CMD java -jar brapimanagementservice-0.0.1-SNAPSHOT.jar